micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/kmg`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true